url: https://msu-cmse-courses.github.io
baseurl: ""

title: CMSE822
author:
  name: Bill Punch
  email: punch@msu.edu
description: > # this means to ignore newlines until "show_excerpts:"
  CMSE822 home page, Fall 2021

show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - Schedule.md
 - Resources.md
 - Syllabus.md
 - Rules.md
 
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
   posts:
      output: true
      permalink: /Weekly/:title

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
#  date_format: "%b %-d, %Y"
  date_format: "%a, %b %d"
  
  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  msu-cmse-courses/cmse822-FS21
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com




